### ISSUE TITLE
spawn C:\WINDOWS\system32\cmd.exe ENOENT

### ISSUE THREAD

**Issue by FILAgiao** [trufflesuite/vscode-ext#109] opened 2022-06-14 15:01 UTC
![image](https://user-images.githubusercontent.com/80993915/173610244-62c2af04-92b2-4237-9991-f43f0e2b0a28.png)
after press the build contract buttom,it shows "spawn C:\WINDOWS\system32\cmd.exe ENOENT"
I do have this cmd.exe at this position,but why????

**Comment by kevinbluer** [comment] 2022-06-21 23:44
Duplicate of #108. Will go ahead and close but feel free to comment on the other thread 👌

**Closed by kevinbluer** 2022-06-21 23:44 UTC
