### ISSUE TITLE
Cannot signed in to Infura account

### ISSUE THREAD

**Issue by luc-murat** [trufflesuite/vscode-ext#175] opened 2022-07-22 08:46 UTC
When I try to create a new network with Infura Service, I have this error message when I click on the "sign in" button : 
**listen EADDRINUSE: address already in use 127.0.0.1:9010**

**Comment by luc-murat** [comment] 2022-07-22 09:50
After some research on the source code, I note that the authorization url used doesn't work right now : 
    **Constants.infuraAuthUrls.baseURL =  'https://oauth.infura.io/'**
The requested route doesn't exist (404).

**Comment by xhulz** [comment] 2022-07-22 13:12
Hey @luc-murat!

Thank you for reaching out! I've just reproduced your steps and I ain't got the error. But after I sign out and sign in again, I've got the error. It seems a problem with the process that hasn't been killed.

Thank you for raising this issue. We will notify you as soon as the problem is resolved.

Cheers!

**Comment by kevinbluer** [comment] 2022-07-22 22:05
Likewise, thanks for raising this @luc-murat! We've seen some occasional quirks with the login flow before so it likely warrants some minor refactoring / improved error handling.

As an interim step, if you're on MacOS / Linux, you can run `kill $(lsof -t -i:9010)` to manually kill the spawned process and try again.

> The requested route doesn't exist (404).

Also just regarding this, I believe that route doesn't accept `GET`'s, hence the `404` response. Note the `POST`'s [here](https://github.com/trufflesuite/vscode-ext/blob/develop/src/services/infuraService/codeFlowLogin.ts#L79).

Thanks again 👍

**Comment by luc-murat** [comment] 2022-08-03 12:39
Hey @xhulz,
I'd like to come back to the problem about "sign in to Infura Account".
After some research on the documentation of VS Code, I believe I found the main reason why I can't use this command.
I suppose that my VS Code configuration is quite different from yours.
I don't use VS Code on the desktop as a developer on Mac OS for example but with a remote configuration based on Windows Subsystem for Linux.
Therefore, my truffle extension host doesn't running locally on Windows but remotely in order to use Ubuntu.
Official documentation confirmed this assumption, it is necessary to follow some good practices to make it work some specific extension features on different hosts. In my case, the specific feature is opening something in a local browser for a particular URI (`Constants.infuraAuthUrls.baseURL`).
In the `codeFlowLogin.ts` file, we're using `open` module launch a browser for particular URI. Instead of relying on a third-party node module, documentation recommend to use `vscode.env.openExternal` from their API.
_Reference_ :  https://code.visualstudio.com/api/advanced-topics/remote-extensions#opening-something-in-a-local-browser-or-application.

Still in the same topic, in one of your test file `truffleTest.test.ts`, you're using `clipboardy` module  to interact the clipboard. It is recommend to use `vscode.env.clipboard.readText()`.

I hope I was clear in my explanations. I can try to open a Pull Request if you want.

Have a great day.

**Comment by xhulz** [comment] 2022-08-04 10:16
Hey @luc-murat,

Thank you again for reaching out to us, and for your thorough research on truffle extension :)

Yes, sure thing! Feel free to put a PR. Please, don't forget to set @kevinbluer @acuarica, @michaeljohnbennett and I as reviewers :)

Thank you again for your contribution

Cheers!

**Comment by acuarica** [comment] 2022-08-09 00:00
Hi @luc-murat, thanks for your feedback.

I was able to reproduce the error, but in a setup slightly different than yours. When I have running both a local and remote (WSL) VS Code instances, and try to sign-in in both, I see the error you mentioned.

![errcon](https://user-images.githubusercontent.com/4592980/183533818-5262ef4f-11d6-4e8a-8947-992a5c611966.gif)

Is this the configuration you have? This setup is running Windows 11 with WSL 1. If not, would you be able to provide your setup?

However, I was not able to reproduce the error when I followed the setup given here https://github.com/trufflesuite/vscode-ext/issues/175#issuecomment-1203896606. I could open the Infura sign-in page from a Remote VS Code running on WSL (watch until the end, the extension takes a bit of time to get activated).

![signin](https://user-images.githubusercontent.com/4592980/183532658-d571406d-b3cc-4d86-ae47-fc0c1a5d229e.gif)

This suggests that the `open` module might not be the problem here. Given said that, I would definitely follow the best practices as you mentioned, and use `vscode.env.openExternal`.

**Comment by luc-murat** [comment] 2022-08-12 09:45
Hi @acuarica,
I've seen your PR :+1:. Thank you for your last comment with screencasts.
To answer your question about my configuration, I was running Windows 11 with WSL2. I'm fed up with this configuration :smile: . I wanted to try but I had several issues about port mapping with other projects. Since then, I replaced Windows with Ubuntu.
For me you can close the issue, the main problem is resolved :+1: 
Last question about the project for my understanding, is the folder `srv/ui-test` still being maintained ?
Have a good day.

**Comment by acuarica** [comment] 2022-08-12 11:07
Hi @luc-murat, thanks for your comment. Sure thing, I'll close this then.

Regarding the `ui-test` folder, not it's not. It's unused code, and it should be removed. It has been on my radar for a while. I'll send another PR to remove it.

**Closed by acuarica** 2022-08-12 11:07 UTC
Labels: error better, refactor

**Comment by acuarica** [comment] 2022-08-12 11:33
As for the `ui-test` folder, here's the PR to remove it https://github.com/trufflesuite/vscode-ext/pull/202.

**Comment by OisinHick** [comment] 2023-04-29 10:29
Hey I'm having a similar error where all I'm trying to do is login to infura for truffle for vscode. I closed WSL which I had open for something separate I was doing and gave it another try. If I'm already logged in it takes me to the API keys page and if I'm not logged in and I try again it gives me "request to https://prod.hydra.internal.infura.org/oauth2/auth/requests/login/accept?login_challenge=1d75b17ca3674474bcb2594e964d3413 failed, reason: getaddrinfo ENOTFOUND prod.hydra.internal.infura.org". Any ideas on a quick fix I can do to get authenticated?
